//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WANAKOKASABOT.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loan
    {
        public int LoanId { get; set; }
        public int ClientId { get; set; }
        public double Loan_Amt { get; set; }
        public int Interest { get; set; }
        public string Term { get; set; }
        public int No_OfPymnt { get; set; }
        public double Deduction { get; set; }
        public double Interested_Amt { get; set; }
        public double Rcv_Amt { get; set; }
        public double Total_Payable { get; set; }
        public System.DateTime Due_Date { get; set; }
        public string Status_Paid { get; set; }
    }
}
